version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Install dependencies..."
      - npm install
  build:
    commands:
      - echo "Run build..."
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist s3://hpctv.ucar.edu --delete --exclude ".htaccess"
#      - aws cloudfront create-invalidation --distribution-id  EUHBNVWX0WXS0 --paths "/*"
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist
