version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: bash ./.circleci/get-sam-data.sh
      - run: git add ./data && git commit -m "Update SAM data" ./data && git push origin ${CIRCLE_BRANCH}

workflows:

  version: 2

  get-sam-data:
    jobs:
      - build:
          context: hpctv
          filters:
            branches:
              only:
                - static-data