version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Get SAM API Data
          command: bash ./.circleci/get-sam-data.sh
      - run:
          name: Commit Data
          command: |
            git config --global user.email "${GITHUB_USER_EMAIL}"
            git config --global user.name "${GITHUB_USER_NAME}"
            git add ./data && git commit -m "Update SAM data" ./data && git push origin ${CIRCLE_BRANCH}

workflows:

  version: 2

  get-sam-data:
    jobs:
      - build:
          context: hpctv
          filters:
            branches:
              only:
                - static-data