version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Get SAM API Data
          command: bash ./.circleci/get-sam-data.sh
      - run:
          name: Commit Data
          command: |
            [[ -z $(git diff ./data) ]] && echo "no changes to commit" && exit 0
            git config --global user.email "${GITHUB_USER_EMAIL}"
            git config --global user.name "${GITHUB_USER_NAME}"
            git remote set-url origin https://${GITHUB_USER_NAME}:${GITHUB_ACCESS_TOKEN}@github.com/NCAR/${CIRCLE_PROJECT_REPONAME}.git
            git add ./data && git commit -m "Update SAM data from CircleCI" ./data && git push origin ${CIRCLE_BRANCH}

workflows:

  version: 2

  get-sam-data:
    jobs:
      - build:
          context: hpctv
          filters:
            branches:
              only:
                - static-data
  nightly:
    triggers:
      - schedule:
          cron: "30 10 * * *"
          filters:
            branches:
              only:
                - static-data
    jobs:
      - build:
          context: hpctv