version: 2
jobs:
  build:
    docker:
      - image: ncar/aws-cli:latest
    steps:
      - checkout
      - run:
          name: Get SAM API Data
          command: |
            bash ./get-sam-data.sh
            JSON_FILES=$(ls -1q ./data/*.json | wc -l)
            if [[ "$JSON_FILES" -ne 13 ]]; then
              echo "Found only $JSON_FILES json files"; exit 1;
            fi
      - run:
          name: Sync Data
          command: |
            eval $(aws ecr get-login --no-include-email --region $AWS_REGION || echo false)
            aws s3 sync ./data s3://hpctv-test.ucar.edu/data --include "*.json"
            aws s3 sync ./data s3://hpctv.ucar.edu/data --include "*.json"

workflows:

  version: 2

  nightly:
    triggers:
      - schedule:
          cron: "30 10 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: hpctv

  development:
    jobs:
      - build:
          context: hpctv
          filters:
            branches:
              only:
                - development